from django.test import (TestCase, TransactionTestCase, tag)
from .models import (UserAccount, Poll, Token, TokenManager) 
import traceback

#Third-party app imports
from model_bakery import baker

'''Test --> models.py'''

#Token and TokenManager:
@tag('token')
class TokenModelTests(TransactionTestCase):

    def setUp(self):
        #Create auxiliary models:
        self.aux_poll = baker.make('api.Poll')
        self.aux_user = baker.make('api.UserAccount')


    def test__generate_token__length(self):
        """
        This test checks whether the token generated by the method TokenManager.generate_token() 
        has length 500.
        """
        token_manager = TokenManager()
        expected_length = 500
        for _ in range(20):
            length = len(token_manager._generate_token())
            self.assertEqual(length, expected_length)

    def test__create_one_token_(self):
        """
        This test tests whether is possible to create a token.
        """
        try:
            new_token = Token.objects.create_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
            token_created = True
            error_msg = ''
        except:
            token_created = False
            new_token = None
            error_msg = traceback.format_exc()
        self.assertIs(token_created, True, error_msg)
        self.assertIsInstance(new_token, Token)
        num_of_tokens = len(Token.objects.all())
        self.assertEqual(num_of_tokens, 1)

    @tag('slow')
    def test__create_one_thousand_tokens_for_the_same_poll(self):
        """
        This test tests whether is possible to create a  thousand tokens.
        """
        for num in range(1, 1001):
            aux_user = baker.make('api.UserAccount')
            new_token = Token.objects.create_token(email=aux_user.ref, poll_id=self.aux_poll.id)
            num_of_tokens = len(Token.objects.all())
            self.assertEqual(num_of_tokens, num)
        num_of_tokens = len(Token.objects.get_queryset().filter(poll=self.aux_poll))
        self.assertEqual(num_of_tokens, 1000)


    def test__create_two_tokens__the_same_poll_and_user(self):
        """
        Must be impossible to create two tokens for the same user in a poll.
        """
        old_token = Token.objects.create_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
        num_of_tokens = len(Token.objects.all())
        self.assertEqual(num_of_tokens, 1)
        new_token = Token.objects.create_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
        num_of_tokens = len(Token.objects.all())
        self.assertEqual(num_of_tokens, 1)
        self.assertEqual(new_token, old_token)
        
    def test__create_50_tokens__the_same_poll_and_user(self):
        """
        Must be impossible to create more than one token for the same user in a poll.
        """
        old_token = Token.objects.create_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
        num_of_tokens = len(Token.objects.all())
        self.assertEqual(num_of_tokens, 1)
        for _ in range(49):
            new_token = Token.objects.create_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
            num_of_tokens = len(Token.objects.all())
            self.assertEqual(num_of_tokens, 1)
            self.assertEqual(new_token, old_token)


    def test__create_tokens_with_wrong_type_arguments(self):
        with self.assertRaises(TypeError):
            Token.objects.create_token(email=123, poll_id=self.aux_poll.id)
        with self.assertRaises(TypeError):
            Token.objects.create_token(email=123, poll_id='Hello')
        with self.assertRaises(TypeError):
            Token.objects.create_token(email=self.aux_user.ref, poll_id='Hello')
        with self.assertRaises(TypeError):
            Token.objects.create_token(None, None)



    def test_get_information_from_token(self):
        original_token = Token.objects.create_token(email=self.aux_user.ref, poll_id=self.aux_poll.id).token
        found_token    = Token.objects.get_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
        self.assertEqual(original_token, found_token)


    def test_get_information_from_50_tokens(self):
        for _ in range(50):
            new_user = baker.make('api.UserAccount')
            new_poll = baker.make('api.Poll')
            original_token = Token.objects.create_token(email=self.aux_user.ref, poll_id=self.aux_poll.id).token
            found_token    = Token.objects.get_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
            self.assertEqual(original_token, found_token)

    def test__get_information_from_nonexistent_poll_user(self):
        found_token    = Token.objects.get_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
        self.assertIsNone(found_token)
        new_user = baker.make('api.UserAccount')
        new_poll = baker.make('api.Poll')
        Token.objects.create_token(email=self.aux_user.ref, poll_id=self.aux_poll.id)
        found_token    = Token.objects.get_token(email=new_user.ref, poll_id=self.aux_poll.id)
        self.assertIsNone(found_token)
        found_token    = Token.objects.get_token(email=self.aux_user.ref, poll_id=new_poll.id)
        self.assertIsNone(found_token)


    def test___get_info_with_wrong_type_arguments(self):
        with self.assertRaises(TypeError):
            Token.objects.get_token(email=123, poll_id=self.aux_poll.id)
        with self.assertRaises(TypeError):
            Token.objects.get_token(email=123, poll_id='Hello')
        with self.assertRaises(TypeError):
            Token.objects.get_token(email=self.aux_user.ref, poll_id='Hello')
        with self.assertRaises(TypeError):
            Token.objects.get_token(None, None)
