# Generated by Django 3.1.2 on 2020-11-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='poll',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
