# Generated by Django 3.1.2 on 2020-11-05 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201105_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poll'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
