# Generated by Django 3.1.4 on 2021-05-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201127_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='permanent_token',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
