# Generated by Django 3.1.4 on 2021-05-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_poll_type_2'),
        ('api', '0005_poll_permanent_token'),
    ]

    operations = [
    ]
