# Generated by Django 3.1.4 on 2021-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_poll_type_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='email_info',
            field=models.TextField(null=True),
        ),
    ]
